### ISSUE TITLE
service banner

### ISSUE THREAD

**Issue by manu-g** [mushorg/snare#42] opened 2016-12-13 09:23 UTC
Hello,
i discovered that aiohttp sets a service banner that looks something like 'Python/3.5 aiohttp/1.1.6'. 
This can be changed as this is only a variable set in aiohttp source.
The corrisbonding file can be found in 
/urs/local/lib/python3.5/dist-packages/aiohttp/protocol.py
in line 539 ( if installed with pip3 in default install location)

regards

**Comment by afeena** [comment] 2016-12-13 09:41
It is possible to set ``Server`` header, as well as another response headers.

for example we can add just one line in https://github.com/mushorg/snare/blob/master/snare.py#L237
``response.add_header('Server', 'cloudflare-nginx')``

**Comment by manu-g** [comment] 2016-12-13 09:55
PORT   STATE SERVICE VERSION
80/tcp open  http    **testing**
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port80-TCP:V=7.31%I=7%D=12/13%Time=584FC36B%P=x86_64-pc-linux-gnu%r(Get
SF:Request,26F,"HTTP/1\.0\x20200\x20OK\r\nContent-Type:\x20text/html\r\nCo
SF:ntent-Length:\x20480\r\nServer:\x20testing\r\nConnection:\x20keep-alive
SF:\r\nDate:\x20Tue,\x2013\x20Dec\x202016\x2009:58:20\x20GMT\r\n\r\n<html>
SF:\n<head>\n<meta\x20content=\"text/html;\x20charset=utf-8\"\x20http-equi
SF:v=\"content-type\">\n\n<meta\
SF:x20content=\"no-cache\"\x20http-equiv=\"cache-control\">\n<meta\x20cont
SF:ent=\"no-cache\"\x20http-equiv=\"pragma\">\n<meta\x20content=\"0\"\x20h
SF:ttp-equiv=\"expires\">\n<meta\x20content=\"0;\x20URL=/Portal/Intro\.htm
SF:l\"\x20http-equiv=\"refresh\">\n</meta></meta></meta></meta></meta></he
SF:ad>\n<body>\n<a\x20href=\"/Portal/Intro\.html\">Click\x20here,\x20when\
SF:r\n\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20you're\x20not\x20aut
SF:omatically\x20redirected</a>\n</body>\n</html>")%r(HTTPOptions,26F,"HTT
SF:P/1\.0\x20200\x20OK\r\nContent-Type:\x20text/html\r\nContent-Length:\x2
SF:0480\r\nServer:\x20testing\r\nConnection:\x20keep-alive\r\nDate:\x20Tue
SF:,\x2013\x20Dec\x202016\x2009:58:20\x20GMT\r\n\r\n<html>\n<head>\n<meta\
SF:x20content=\"text/html;\x20charset=utf-8\"\x20http-equiv=\"content-type
SF:\">\n\n<meta\x20content=\"no-
SF:cache\"\x20http-equiv=\"cache-control\">\n<meta\x20content=\"no-cache\"
SF:\x20http-equiv=\"pragma\">\n<meta\x20content=\"0\"\x20http-equiv=\"expi
SF:res\">\n<meta\x20content=\"0;\x20URL=/Portal/Intro\.html\"\x20http-equi
SF:v=\"refresh\">\n</meta></meta></meta></meta></meta></head>\n<body>\n<a\
SF:x20href=\"/Portal/Intro\.html\">Click\x20here,\x20when\r\n\x20\x20\x20\
SF:x20\x20\x20\x20\x20\x20\x20\x20\x20you're\x20not\x20automatically\x20re
SF:directed</a>\n</body>\n</html>")%r(RTSPRequest,15C,"HTTP/1\.1\x20400\x2
SF:0Bad\x20Request\r\nContent-Type:\x20text/html;\x20charset=utf-8\r\nCont
SF:ent-Length:\x20133\r\nConnection:\x20close\r\nDate:\x20Tue,\x2013\x20De
SF:c\x202016\x2009:58:20\x20GMT\r\nServer:**\x20\x20Siemens\x20315-2PN/DP\x2
SF:0programmable\x20logic\x20controller\x20http\x20admin**\r\n\r\n\n<html>\n
SF:\x20\x20<head>\n\x20\x20\x20\x20<title>400\x20Bad\x20Request</title>\n\
SF:x20\x20</head>\n\x20\x20<body>\n\x20\x20\x20\x20<h1400\x20Bad\x20Reque
SF:st</h1>\n\x20\x20\x20\x20Bad\x20Request\n\x20\x20</body>\n</html>");

       if content:
                response.add_header('Content-Length', str(len(content)))
       response.add_header('Server', 'testing')
       response.send_headers()

I checked your suggestion and added the server header. I think it is easier to adjust the aiohttp source code and replace the variable there.

**Comment by glaslos** [comment] 2016-12-13 10:27
I'd actually recommend to not change the aiohttp source code. This would mean we have to maintain the fork and merge future changes to the library.

**Comment by afeena** [comment] 2016-12-13 10:57
nmap-service-probes database is [open](https://svn.nmap.org/nmap/nmap-service-probes), so I it might be possible to understand what we should return to change service.

For example, I changes server header to nginx, and I now have no errors in nmap

```
nmap -sV -T4 -F localhost

Starting Nmap 7.31 ( https://nmap.org ) at 2016-12-13 10:51 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000020s latency).
Other addresses for localhost (not scanned): ::1
rDNS record for 127.0.0.1: localhost.localdomain
Not shown: 98 closed ports
PORT     STATE SERVICE     VERSION
22/tcp   open  ssh         OpenSSH 7.3 (protocol 2.0)
8080/tcp open  http-proxy?

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 35.03 seconds
```

**Comment by afeena** [comment] 2016-12-13 11:08
Moreover, I fix some problems and get

```
nmap -sV -T4 -F localhost

Starting Nmap 7.31 ( https://nmap.org ) at 2016-12-13 11:06 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000030s latency).
Other addresses for localhost (not scanned): ::1
rDNS record for 127.0.0.1: localhost.localdomain
Not shown: 98 closed ports
PORT     STATE SERVICE VERSION
22/tcp   open  ssh     OpenSSH 7.3 (protocol 2.0)
8080/tcp open  http    nginx
```

**Comment by glaslos** [comment] 2016-12-13 12:00
shall we add the server header as an optional flag?

**Comment by afeena** [comment] 2016-12-13 12:03
I think it will be good feature :)

**Comment by manu-g** [comment] 2016-12-13 12:05
I have an equal error and get an output like 
 http?
what local errors did you fix?

**Comment by afeena** [comment] 2016-12-13 12:10
@manu-g 
It was an error in TANNER config (I forgot to replace old config with new config), so, I fixed TANNER and when start SNARE

**Comment by glaslos** [comment] 2020-03-19 11:54
Duplicate of #7

**Closed by glaslos** 2020-03-19 11:54 UTC
