### ISSUE TITLE
500 Internal Server Error Server

### ISSUE THREAD

**Issue by kont45** [mushorg/snare#180] opened 2019-02-27 07:39 UTC
Hi. I'm trying to run Snare honeypot. I cloned a few website but at all I get 500 error server.

**Comment by q2dg** [comment] 2019-02-28 18:23
I have the same issue!

**Comment by rnehra01** [comment] 2019-03-01 10:16
The issue is due to Tanner. Snare send all requests to a tanner service (tanner.mushmush.org default tanner if you do not start your own tanner instance) and tanner response is invalid, so if you start your own Tanner instance using https://github.com/mushorg/tanner, it will work.
@afeena Do you know why default tanner isn't working properly.

**Comment by viskey98** [comment] 2019-03-01 12:12
It seems the default tanner server is not running at all. @glaslos is there any reason for the server being down?
@rnehra01 for a hotfix, I think if you can host a tanner instance in some free server (if possible) and let new-comers use it as a default tanner, before they get acquainted with tanner.
What do you think about this?

**Comment by afeena** [comment] 2019-03-01 13:25
Now fixed

**Comment by rnehra01** [comment] 2019-03-01 18:45
To make the snare work fine just for copying it and just serving it, I think we can provide an option to run snare without any tanner instance. @afeena @glaslos @viskey98 ?

**Comment by kont45** [comment] 2019-03-01 19:28
> 
> 
> To make the snare work fine just for copying it and just serving it, I think we can provide an option to run snare without any tanner instance. @afeena @glaslos @viskey98 ?

Briliant idea.

**Comment by viskey98** [comment] 2019-03-02 14:49
>To make the snare work fine just for copying a website and just serving it, I think we can provide an option to run snare without any tanner instance. @afeena @glaslos @viskey98 ?  

I think in my opinion, our honeypot is SNARE-TANNER, than SNARE & TANNER. What do I mean by this?  
- I mean that this honeypot without TANNER is not a honeypot at all. TANNER  is the master-mind and SNARE is just the surface.
- If this is just for testing SNARE (for beginners mostly), that's why we have default tanner, for serving the purpose of just dealing with SNARE without installing TANNER. So having an option to run SNARE without tanner, is just a simple web-server and doesn't do much good in the Honeypot's point of view.
- More over SNARE doesn't store any of the session details but sends it to TANNER. Thus a user who wants to use SNARE without TANNER, can better use his own simple web-server with his own session storing mechanism, instead of using SNARE without TANNER.

`To make the snare work fine just for copying a website and just serving it.`

- I think default TANNER is meant for this purpose (because a user using in production won't use default-tanner obviously), and assuming default tanner works fine (which it should), it will be enough to check if a user's SNARE works fine.
- In a honeypot's point of view this is not gonna bring much good for it. And from my perspective we need to change a good amount of code to create this feature (at the moment SNARE relies completely on TANNER  for dealing with the response), but it might make the code-base more complicated, which may not be worth it for the same.

And yeah, this is just my opinion. I hope others will have theirs as well. :)

**Comment by rnehra01** [comment] 2019-03-02 16:23
Yup, agree that amount of code change may not worth it.

**Closed** 2019-04-03 20:16 UTC
