### ISSUE TITLE
docker-compose is error

### ISSUE THREAD

**Issue by Belee05** [mushorg/snare#228] opened 2020-01-22 08:10 UTC
Ubuntu 18.04 LTS 
When I execute an order docker-compose build, have some error.How can I fix these error?
![image](https://user-images.githubusercontent.com/51012725/72877036-ebaf1300-3d32-11ea-9323-27e8ca05abb2.png)

`ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2tw3g_p0/yarl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2tw3g_p0/yarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vz71b9_n
       cwd: /tmp/pip-install-2tw3g_p0/yarl/
  Complete output (37 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/yarl
  copying yarl/quoting.py -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.6/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/_quoting.html'
  warning: no previously-included files found matching 'yarl/_quoting.*.so'
  warning: no previously-included files found matching 'yarl/_quoting.pyd'
  warning: no previously-included files found matching 'yarl/_quoting.*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/_quoting.c -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/_quoting.pyx -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.6/yarl
  running build_ext
  building 'yarl._quoting' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/yarl
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c yarl/_quoting.c -o build/temp.linux-x86_64-3.6/yarl/_quoting.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl`

**Comment by afeena** [comment] 2020-01-26 20:03
Hi @Belee05 
Unfortunately, I can't reproduce your problem. Is it your full log? How you run compose?

**Comment by pch0n** [comment] 2020-01-29 18:43
Hi, I just got the exact same log errors.
Debian 10 updated, docker and docker-compose installed with default settings.
I cloned the repo, launched "docker-compose build" from the cloned directory and got the exact same result.

Here is the full log after the first encountered error:

`  Building wheel for yarl (setup.py): started
Building wheel for yarl (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9kv6m68g/yarl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9kv6m68g/yarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kiyx05l3
       cwd: /tmp/pip-install-9kv6m68g/yarl/
  Complete output (37 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/yarl
  copying yarl/quoting.py -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.6/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/_quoting.html'
  warning: no previously-included files found matching 'yarl/_quoting.*.so'
  warning: no previously-included files found matching 'yarl/_quoting.pyd'
  warning: no previously-included files found matching 'yarl/_quoting.*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/_quoting.c -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/_quoting.pyx -> build/lib.linux-x86_64-3.6/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.6/yarl
  running build_ext
  building 'yarl._quoting' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/yarl
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c yarl/_quoting.c -o build/temp.linux-x86_64-3.6/yarl/_quoting.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl
  Running setup.py clean for yarl
  Building wheel for idna-ssl (setup.py): started
  Building wheel for idna-ssl (setup.py): finished with status 'done'
  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-py3-none-any.whl size=3159 sha256=03eff665ad4d500f6a7a68a29ecd720c5e060f3206c467b9068988049f247a2e
  Stored in directory: /tmp/pip-ephem-wheel-cache-bk3le92q/wheels/6a/f5/9c/f8331a854f7a8739cf0e74c13854e4dd7b1af11b04fe1dde13
  Building wheel for multidict (PEP 517): started
  Building wheel for multidict (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpoedvum63
       cwd: /tmp/pip-install-9kv6m68g/multidict
  Complete output (43 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_compat.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_abc.py -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/__init__.py -> build/lib.linux-x86_64-3.6/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/_multidict.c -> build/lib.linux-x86_64-3.6/multidict
  copying multidict/py.typed -> build/lib.linux-x86_64-3.6/multidict
  creating build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-x86_64-3.6/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/multidict
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c multidict/_multidict.c -o build/temp.linux-x86_64-3.6/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for multidict
  Building wheel for MarkupSafe (setup.py): started
  Building wheel for MarkupSafe (setup.py): finished with status 'done'
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-py3-none-any.whl size=12629 sha256=e7da6aae84c028ae2cc5f550579b9efdc042fbab668a1b4c62dee504faf17c46
  Stored in directory: /tmp/pip-ephem-wheel-cache-bk3le92q/wheels/ca/85/2f/4c3a8ca6fb5eec7b43ec1e5666c7274dcdb86d6c32231aaa9d
Successfully built aiohttp idna-ssl MarkupSafe
Failed to build yarl multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly
ERROR: Service 'snare' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`

**Comment by afeena** [comment] 2020-01-31 18:38
#231 
Check please and let me know if it solves your problem

**Comment by pch0n** [comment] 2020-01-31 19:29
Working perfectly for me now !
Thanks for your help

**Comment by afeena** [comment] 2020-01-31 19:39
@pch0n perfect! Thanks for letting me know :) I will merge into master then :)

**Comment by mzfr** [comment] 2020-02-24 16:08
@afeena @rjt-gupta I think we can close this issue.

**Closed** 2020-02-25 22:56 UTC
